# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dm-rspec2"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Siddharth Sharma"]
  s.date = "2013-03-17"
  s.description = "RSpec2 matchers for DataMapper"
  s.email = "svs@svs.io"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGELOG.markdown",
    "GPL-LICENSE.txt",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/dm-rspec2.rb",
    "lib/dm/matchers.rb",
    "lib/dm/matchers/belong_to.rb",
    "lib/dm/matchers/have_many.rb",
    "lib/dm/matchers/have_many_and_belong_to.rb",
    "lib/dm/matchers/have_many_through.rb",
    "lib/dm/matchers/have_one.rb",
    "lib/dm/matchers/have_property.rb",
    "lib/dm/matchers/validate_format_of.rb",
    "lib/dm/matchers/validate_inclusion_of.rb",
    "lib/dm/matchers/validate_presence_of.rb",
    "lib/dm/matchers/validate_uniqueness_of.rb",
    "lib/dm/matchers/validation_matcher.rb",
    "lib/dm/resource.rb",
    "spec/dm/matchers/belong_to_spec.rb",
    "spec/dm/matchers/errors_on_spec.rb",
    "spec/dm/matchers/have_many_and_belong_to_spec.rb",
    "spec/dm/matchers/have_many_spec.rb",
    "spec/dm/matchers/have_many_through_spec.rb",
    "spec/dm/matchers/have_one_spec.rb",
    "spec/dm/matchers/have_property_spec.rb",
    "spec/dm/matchers/validate_format_of_spec.rb",
    "spec/dm/matchers/validate_inclusion_of_spec.rb",
    "spec/dm/matchers/validate_presence_of_spec.rb",
    "spec/dm/matchers/validate_uniquness_of_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/svs/dm-rspec2"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "It's a set of RSpec2 matchers for DataMapper. Something similar to rspec-rails gem."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, [">= 0"])
      s.add_runtime_dependency(%q<dm-types>, [">= 0"])
      s.add_runtime_dependency(%q<dm-validations>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<reek>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<libnotify>, [">= 0"])
      s.add_development_dependency(%q<debugger>, [">= 0"])
      s.add_development_dependency(%q<dm-migrations>, [">= 0"])
      s.add_development_dependency(%q<dm-sqlite-adapter>, [">= 0"])
    else
      s.add_dependency(%q<dm-core>, [">= 0"])
      s.add_dependency(%q<dm-types>, [">= 0"])
      s.add_dependency(%q<dm-validations>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<reek>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<libnotify>, [">= 0"])
      s.add_dependency(%q<debugger>, [">= 0"])
      s.add_dependency(%q<dm-migrations>, [">= 0"])
      s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
    end
  else
    s.add_dependency(%q<dm-core>, [">= 0"])
    s.add_dependency(%q<dm-types>, [">= 0"])
    s.add_dependency(%q<dm-validations>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<reek>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<libnotify>, [">= 0"])
    s.add_dependency(%q<debugger>, [">= 0"])
    s.add_dependency(%q<dm-migrations>, [">= 0"])
    s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
  end
end

